apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-helm
  # these are replica set labels
  labels:
    purpose: helm-demo
    project: {{ .Values.common.project }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    # these labels are used to select pods
    matchLabels:
      purpose: helm-demo
      project: {{ .Values.common.project }}
  # pod definition
  template:
    metadata:
      labels:
        # purpose: dp-demo
        purpose: helm-demo
        project: {{ .Values.common.project }}
    spec:
      containers:
      - name: nginx
        image: nginx:{{ .Values.deployment.imageVersion }}